import type { Metadata } from "next";
import Footer from "@/components/layout/Footer";
import Header from '@/components/layout/Header'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased bg-screen`}
    >
      <header className="w-full bg-transparent px-4 py-4 sm:px-6"><Header /></header>
      <body className="min-h-full flex flex-col pb-17">{children}</body>
      <footer><Footer /></footer>
    </html>
  );
}
