import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const futura = localFont({
  src: [
    // --- LIGHT (300) ---
    {
      path: './fonts/Futura/FuturaLightC.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Futura/FuturaLightC-Italic.woff',
      weight: '300',
      style: 'italic',
    },

    // --- BOOK / REGULAR (400) ---
    {
      path: './fonts/Futura/FuturaBookC.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Futura/FuturaBookC-Italic.woff',
      weight: '400',
      style: 'italic',
    },

    // --- MEDIUM (500) ---
    {
      path: './fonts/Futura/FuturaMediumC.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Futura/FuturaMediumC-Italic.woff',
      weight: '500',
      style: 'italic',
    },

    // --- DEMI / SEMIBOLD (600) ---
    {
      path: './fonts/Futura/FuturaDemiC.woff',
      weight: '600', // Для Demi лучше использовать 600 (Semibold)
      style: 'normal',
    },
    {
      path: './fonts/Futura/FuturaDemiC-Italic.woff',
      weight: '600',
      style: 'italic',
    },
  ],
  variable: '--font-futura', // Имя CSS-переменной для интеграции с Tailwind
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${futura.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
